Gestor2 maga
elmanuchuky/TP_Cursos_en_Curso pull request #26
Opened 2017-10-22 08:50 UTC by MagaPache

2017-10-22 19:54 UTC, fernandodelima requested changes

2017-10-22 19:54 UTC, elmanuchuky commented on Project/Desktop/src/Model/GestorAsistencia.java
> +        comando.close();
lo cerras sin haber llamado al metodo executeUpdate(), entonces no haria nada al final de cuentas

2017-10-22 19:54 UTC, elmanuchuky commented on Project/Desktop/src/Model/GestorAsistencia.java
> +         ResultSet consulta = comando.executeQuery("exec sp_listado_asistencia_filtros " + idCurso +" "+ fecha +" "+ email);
que onda con esa consulta? no usan preparedStmt, de ultima deberian tener separaciones por coma

2017-10-22 19:54 UTC, elmanuchuky commented on Project/Desktop/src/Model/vwAsistenciaMostrar.java
> +    }
si es para mostrar no deberia tener un toString() custom? o donde se mostraria?

2017-10-22 19:54 UTC, elmanuchuky commented on Project/Desktop/src/Model/GestorAsistencia.java
> +         //(apellido + nombre Cursante), fecha_asistencia y si esta_presente o no
tener cuidado aca, los distintos filtros traerian cosas que no contemplan en la view

2017-10-22 19:56 UTC, elmanuchuky commented on Project/Desktop/src/Model/GestorAsistencia.java
> +         //(apellido + nombre Cursante), fecha_asistencia y si esta_presente o no
me refiero a que capaz se debe hacer en distintos metodos lo que se desea

2017-10-22 19:57 UTC, elmanuchuky commented on Project/Desktop/src/Model/vwAsistenciaMostrar.java
> +    }
si no es en combo, y no se usa para seleccionar para luego modificar, no habria problemas

2017-10-23 16:07 UTC, MagaPache commented on Project/Desktop/src/Model/GestorAsistencia.java
> +        comando.close();
my bad jeje

2017-10-23 16:08 UTC, MagaPache commented on Project/Desktop/src/Model/GestorAsistencia.java
> +         //(apellido + nombre Cursante), fecha_asistencia y si esta_presente o no
fair enough, corregido y separado

2017-10-23 16:09 UTC, MagaPache commented on Project/Desktop/src/Model/vwAsistenciaMostrar.java
> +    }
en realidad este lo hice por ósmosis xq no lo vamos a usar jeje

2017-10-23 16:14 UTC, MagaPache commented
Listo para nueva review capitán

2017-10-25 03:36 UTC, closed without merging